<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWV6cly6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWV6cly6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWV6cly6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWV6cly6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWV6cly6\App_KernelDevDebugContainer([
    'container.build_hash' => 'WV6cly6',
    'container.build_id' => 'a9ea816a',
    'container.build_time' => 1621578235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWV6cly6');
